### PR TITLE
Create a proper test for flink-sql-examples

### PR DESCRIPTION
**Pull request by kornys**

### CODE REVIEW

**Review by Frawless — APPROVED** [review]

**Review by tinaselenge — APPROVED** [review]
LGTM. I guess, in the future when we add examples with simpler SQL queries, we can check for more specific messages in the output topic.

**Comment by kornys** [comment]
> LGTM. I guess, in the future when we add examples with simpler SQL queries, we can check for more specific messages in the output topic.

yeah sure, this just starting point with example, in future we will use proper clients, flink deployments created by builders etc... :)

**Pull request merged**
